### ISSUE TITLE
Farm not started

### ISSUE THREAD

**Issue by Nord1cWarr1or** [consolko/TonStation_bot#3]
```
2024-09-09 16:52:45 | INFO     | tapper  :259 | x | Login successful
{'code': 200, 'message': 'success', 'data': {'userId': 'x', 'token': 'soon', 'amount': '28.8', 'timeStart': '2024-09-09T16:52:45.619Z', 'timeEnd': '2024-09-10T00:52:45.619Z', 'isClaimed': False, '_id': 'x', 'createdAt': '2024-09-09T16:52:45.619Z', 'updatedAt': '2024-09-09T16:52:45.619Z', '__v': 0}}
2024-09-09 16:52:45 | WARNING  | tapper  :296 | x | Farm not started...
2024-09-09 16:52:45 | INFO     | tapper  :340 | x | sleep 60.0 min
```

**Comment by Nord1cWarr1or** [comment]
Почему Farm not started?
Или это не ошибка, а просто фарм не окончен еще?
Если так, добавь пж сообщение об этом, а то сбивает с толку. Ну либо вычислить время слипа, чтоб бот заходил в нужное время уже.

**Comment by parafius** [comment]
тоже самое, ток после логина {'code': 200, 'message': 'success', 'data': 'jwt malformed'}

**Comment by consolko** [comment]
@Nord1cWarr1or Текст поменяю, это появляется когда сервер игры запрос принял корректно, но из-за лагов ответил как-то не так. Если зайти в игру, то видно что фарм идет.

**Comment by consolko** [comment]
> тоже самое, ток после логина {'code': 200, 'message': 'success', 'data': 'jwt malformed'}
Затрудняюсь сказать, у меня такой ошибки ни разу не было. Возможно и сам сервак глючит.

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or Текст поменяю, это появляется когда сервер игры запрос принял корректно, но из-за лагов ответил как-то не так. Если зайти в игру, то видно что фарм идет.

Понял, спасибо
